import os
import json
from typing import List
from urllib.parse import urlparse

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, HttpUrl
from openai import OpenAI


app = FastAPI(title="ShwayGo Engine API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

client = None


class ProductRequest(BaseModel):
    product_url: HttpUrl


class ProductResponse(BaseModel):
    processing_status: str
    current_percentage: int
    product_rating: float
    description: str
    names: List[str]
    seo_assets: List[str]
    faq_assets: List[str]
    reviews_assets: List[str]
    features: List[str]
    specifications: List[str]
    images: List[str]
    videos: List[str]


def detect_source(product_url: str) -> str:
    domain = urlparse(product_url).netloc.lower()

    if "aliexpress" in domain:
        return "AliExpress"
    if "amazon" in domain:
        return "Amazon"
    if "temu" in domain:
        return "Temu"
    if "cj" in domain or "cjdropshipping" in domain:
        return "CJ Dropshipping"

    return "Unknown Store"


def scrape_product_basic(product_url: str) -> dict:
    source = detect_source(product_url)

    return {
        "source": source,
        "product_url": product_url,
        "raw_title": f"Product from {source}",
        "raw_description": "Supplier product page detected. Detailed extraction will be expanded in the next backend phase.",
        "raw_images": [],
        "raw_videos": [],
        "raw_rating": 4.8,
    }


def fallback_package(scraped: dict) -> dict:
    source = scraped["source"]

    return {
        "processing_status": "completed",
        "current_percentage": 100,
        "product_rating": scraped.get("raw_rating", 4.8),
        "description": f"Store-ready product description prepared by ShwayGo for a product sourced from {source}.",
        "names": [
            f"Trending {source} Product",
            "Store-Ready Winning Product",
            "Smart Viral Product Pick"
        ],
        "seo_assets": [
            "trending ecommerce product",
            "best product for online store",
            "viral product for social media"
        ],
        "faq_assets": [
            "Q: Is this product suitable for online selling? A: Yes, it is prepared for ecommerce use.",
            "Q: Can I edit the product content? A: Yes, all generated content can be reviewed and edited."
        ],
        "reviews_assets": [
            "Great product and very useful for daily needs.",
            "Good quality and suitable for online store customers."
        ],
        "features": [
            "Prepared for ecommerce listing",
            "Suitable for social media promotion",
            "Can be reviewed and edited before publishing"
        ],
        "specifications": [
            f"Source: {source}",
            "Content status: Generated by ShwayGo",
            "Usage: Ecommerce product package"
        ],
        "images": scraped.get("raw_images", []),
        "videos": scraped.get("raw_videos", []),
    }


def generate_with_ai(scraped: dict) -> dict:
    if not os.getenv("OPENAI_API_KEY"):
        return fallback_package(scraped)

    prompt = f"""
You are ShwayGo Engine, an ecommerce product preparation engine.

Create a complete store-ready product package from this product data.

Source: {scraped["source"]}
Product URL: {scraped["product_url"]}
Raw title: {scraped["raw_title"]}
Raw description: {scraped["raw_description"]}

Return ONLY valid JSON with exactly these keys:
processing_status, current_percentage, product_rating, description,
names, seo_assets, faq_assets, reviews_assets, features,
specifications, images, videos.

Rules:
- processing_status must be "completed".
- current_percentage must be 100.
- product_rating must be a number.
- description must be one long ecommerce product description.
- names must be a list of 3 attractive product names.
- seo_assets must be a list of SEO keywords and phrases.
- faq_assets must be a list of Q&A strings.
- reviews_assets must be a list of realistic review-style strings.
- features must be a list of product benefits.
- specifications must be a list of product specifications.
- images must only contain real image URLs from the source data. If none, return [].
- videos must only contain real video URLs from the source data. If none, return [].
- Do not invent fake image or video URLs.
"""

    try:
        response = client.responses.create(
            model="gpt-4o-mini",
            input=prompt,
        )

        text = response.output_text.strip()

        if text.startswith("```"):
            text = text.replace("```json", "").replace("```", "").strip()

        data = json.loads(text)

        required_keys = [
            "processing_status",
            "current_percentage",
            "product_rating",
            "description",
            "names",
            "seo_assets",
            "faq_assets",
            "reviews_assets",
            "features",
            "specifications",
            "images",
            "videos",
        ]

        for key in required_keys:
            if key not in data:
                raise ValueError(f"Missing key: {key}")

        return data

    except Exception:
        return fallback_package(scraped)


@app.get("/")
def health_check():
    return {"status": "ShwayGo Engine API is running"}


@app.post("/fetch-product", response_model=ProductResponse)
def fetch_product(payload: ProductRequest):
    product_url = str(payload.product_url)

    if not product_url:
        raise HTTPException(status_code=400, detail="product_url is required")

    scraped = scrape_product_basic(product_url)
    package = generate_with_ai(scraped)

    return package
